# Generated by Django 5.2.8 on 2026-01-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['zone', 'row', 'number']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tickets',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=30, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='events.seat'),
        ),
        migrations.AddField(
            model_name='seat',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='zone',
            field=models.CharField(choices=[('parter', 'Партер'), ('loge_left', 'Ложа левая'), ('loge_right', 'Ложа правая'), ('balcony', 'Балкон')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('event', 'zone', 'row', 'number')},
        ),
    ]
