# Generated by Django 5.2.8 on 2026-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_create_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_desc',
            field=models.TextField(blank=True, verbose_name='Описание гостя программы'),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_image',
            field=models.ImageField(blank=True, null=True, upload_to='guests/', verbose_name='Фото гостя программы'),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название блока гостя'),
        ),
        migrations.AddField(
            model_name='event',
            name='performer_1_desc',
            field=models.TextField(blank=True, verbose_name='Описание первого блока участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='performer_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='performers/', verbose_name='Фото первого блока участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='performer_1_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название первого блока участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='performer_2_desc',
            field=models.TextField(blank=True, verbose_name='Описание второго блока участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='performer_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='performers/', verbose_name='Фото второго блока участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='performer_2_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название второго блока участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.TextField(blank=True, verbose_name='Концертная программа'),
        ),
    ]
