# Generated by Django 5.2.8 on 2026-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_guest_desc_event_guest_image_event_guest_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='events.seat'),
        ),
    ]
